### ISSUE TITLE
Enabling italic fonts in iTerm 2, tmux, and vim

### ISSUE THREAD

**Issue by alexpearce** [alexpearce/alexpearce.github.com#23]
Comment thread for post [Enabling italic fonts in iTerm 2, tmux, and vim](https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/).

Comments made before 18 February 2021 were imported from Disqus using an [import script](https://gist.github.com/alexpearce/ff0b5e9f1c0816d7009985dfa0dcaa19). The datetimes and authors of the imported comments do not reflect the values of the original comments.

**Comment by alexpearce** [comment]
_Comment № 1 originally by signalpillar at 2014-10-02 07:46:56 UTC_.

Superb post. Thanks!

**Comment by alexpearce** [comment]
_Comment № 2 originally by Menor at 2014-10-17 06:49:38 UTC_.

Just wanted to say thank you, this helped a lot.

**Comment by alexpearce** [comment]
_Comment № 3 originally by Xavier Cambar at 2014-11-25 16:40:42 UTC_.

Makes everything so much better. Thanks you!

**Comment by alexpearce** [comment]
_Comment № 4 originally by Dom at 2014-12-04 23:12:13 UTC_.

This works but for some reason, messes up the colors in vim...

**Comment by alexpearce** [comment]
_Comment № 5 originally by tarunnurat at 2014-12-14 09:02:47 UTC_.

This worked great. Thanks so much.

**Comment by alexpearce** [comment]
_Comment № 6 originally by April Arcus at 2015-01-26 19:59:16 UTC_.

Great post. I happen to use gnu ls for colorized output and found that after setting

  
export TERM='xterm-256color-italic';  
in my bashrc, dircolors failed to set $LS\_COLORS correctly. I fixed this by invoking it in a subshell:

  
eval $(TERM=xterm-256color dircolors ~/.dircolors)

**Comment by alexpearce** [comment]
_Comment № 7 originally by Alex Pearce at 2015-01-27 07:37:28 UTC, replying to [a comment by April Arcus at 2015-01-26 19:59:16 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512353)_.

Good catch and a nice solution, thanks!

**Comment by alexpearce** [comment]
_Comment № 8 originally by pepper_chico at 2015-01-27 21:06:10 UTC_.

Thanks!

**Comment by alexpearce** [comment]
_Comment № 9 originally by Seth Messer at 2015-03-20 03:40:09 UTC_.

so i'm almost positive there is something up with either my vim colorscheme or the iterm2 "itermcolors" palette, but none the less, i'm seeing italics when echo'ing the "test" command in both tmux and a straight shell; however, in vim with the highlight rule i'm getting a gray background for comments, white foreground and no italics (rather than normally a muted gray foreground and transparent background). other than that, really cool! (any thoughts on a fix for the vim issue i noted?)

**Comment by alexpearce** [comment]
_Comment № 10 originally by Alex Pearce at 2015-03-21 21:26:16 UTC, replying to [a comment by Seth Messer at 2015-03-20 03:40:09 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512452)_.

If the tput command produced correct-looking output then I'm not sure why Vim wouldn't like it. The only thing I can think of is if you're using a *really* old version of Vim.

**Comment by alexpearce** [comment]
_Comment № 11 originally by Seth Messer at 2015-03-21 21:27:45 UTC, replying to [a comment by Alex Pearce at 2015-03-21 21:26:16 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512478)_.

nah, i'm up to date on everything on homebrew..

vim --version  
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 23 2015 18:03:39)

At any rate, no biggy. was a nice to have, but not a huge huge deal for me. thanks tons for the article though. was insightful none the less! :)

**Comment by alexpearce** [comment]
_Comment № 12 originally by Ronak Gandhi at 2015-04-16 21:06:35 UTC_.

Thanks for the post.

I have it working everywhere except for inside tmux. Followed all the steps, but still italics don't work inside tmux.

**Comment by alexpearce** [comment]
_Comment № 13 originally by Bric3 at 2015-04-21 15:26:27 UTC_.

Another thing that may be wrong, patched font may not have an Italic variant, like "Menlo for Powerline"

**Comment by alexpearce** [comment]
_Comment № 15 originally by Alex Pearce at 2015-04-22 07:09:49 UTC, replying to [a comment by Ronak Gandhi at 2015-04-16 21:06:35 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512537)_.

Hmm, when I follow the steps again everything seems to work. You might need to restart your tmux server (with tmux kill-server). Does the value of $TERM within tmux say screen-256color-italic as it should, or something different?

**Comment by alexpearce** [comment]
_Comment № 16 originally by Alex Pearce at 2015-04-22 07:10:12 UTC, replying to [a comment by Brice at 2015-04-21 15:30:52 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512604)_.

Yep! You will need a font that supports italics.

**Comment by alexpearce** [comment]
_Comment № 17 originally by Ronak Gandhi at 2015-04-22 16:21:28 UTC, replying to [a comment by Alex Pearce at 2015-04-22 07:09:49 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512633)_.

The problem was screen-256color terminfo. That itself was not available on my remote system. Fixing that fixed my issue.

Thanks.

**Comment by alexpearce** [comment]
_Comment № 18 originally by dpomondo at 2015-04-28 23:36:24 UTC_.

This is absolutely fantastic and works flawlessly... right until I start vim INSIDE tmux. Then I get a 'terminal entry not found in terminfo' error and it defaults to ansi.

Vim OUTSIDE of tmux is working great though -- that in itself makes me very happy, thank you.

edit: False alarm. Reran tic outside of tmux as superuser, and the terminfo entry complied just fine. As the lego minifigs say: Everything is awesome!

**Comment by alexpearce** [comment]
_Comment № 19 originally by Alex Pearce at 2015-04-29 05:58:53 UTC, replying to [a comment by dpomondo at 2015-04-28 23:36:24 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512734)_.

Hi! Ronak Gandhi reported a similar problem above, so I'll just repeat what I said there:


> You might need to restart your tmux server (with tmux kill-server). Does the value of $TERM within tmux say screen-256color-italic as it should, or something different?

**Comment by alexpearce** [comment]
_Comment № 20 originally by Brice at 2015-05-12 16:17:42 UTC_.

With SSH regardless of tmux, environment may be passed on the remote and it is probable the remote doesn't know this terminal. A possible solution on the local host is to alias ssh or a function

```

alias ssh="TERM=xterm-256color ssh"

```

**Comment by alexpearce** [comment]
_Comment № 21 originally by cwalkatron at 2015-05-22 18:03:34 UTC_.

Thanks so much.

**Comment by alexpearce** [comment]
_Comment № 22 originally by timfeirg at 2015-09-27 15:34:44 UTC_.

great post, however this yields a minor issue on mac with brew, as it complains   



> tput: unknown terminal "xterm-256color-italic"  
whenever I 

brew install anything

**Comment by alexpearce** [comment]
_Comment № 23 originally by Alex Pearce at 2015-09-27 17:40:05 UTC, replying to [a comment by timfeirg at 2015-09-27 15:34:44 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512870)_.

Thanks for reporting! I just saw the same thing yesterday. It must have been introduced in a recent Homebrew update. You'll see similar messages when connecting to a host without the entry in the TERM database from a host that does have it (like when ssh'ing from your local machine).

I thought every process that Homebrew would run would ‘inherit’ all the necessary information from the parent session (one where italics *do* work), so I don't understand what's going on. Could be a Homebrew bug I suppose, but I would need to dig around to try find a cause/commit to make the bug request more helpful to the Homebrew team…

**Comment by alexpearce** [comment]
_Comment № 24 originally by Sitaktif at 2015-10-23 06:00:40 UTC_.

Instead of registering a new terminfo, a possibility is to override the Vim codes like this:

if has('macunix') || system('uname -o') =~? '^darwin'  
 set t\_ZH=^[[3m t\_ZR=^[[23m " Set the italics code

endif

Note that for the escape sequences, you have to type on the keyboard: <c-v><esc>[3m (the ^[ is a litteral <esc>)

See :h t\_ZH for more info.

It is not a perfect solution though because it will just assume that the terminal supports this escape sequence, which won't be the case if you use [Terminal.app](http://Terminal.app "Terminal.app") for example, though in the case of [Terminal.app](http://Terminal.app "Terminal.app"), the sequence is simply ignored so no big deal.

**Comment by alexpearce** [comment]
_Comment № 25 originally by Alex Pearce at 2015-10-25 11:35:14 UTC, replying to [a comment by Sitaktif at 2015-10-23 06:00:40 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512937)_.

Great tip! This does enable italics for me outside of tmux 2.1, but not inside. tmux 2.1 seems to cause all sorts of problems for me, though.

**Comment by alexpearce** [comment]
_Comment № 26 originally by Kenny Kaye at 2015-11-02 18:00:01 UTC, replying to [a comment by Alex Pearce at 2015-10-25 11:35:14 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512965)_.

2.1 seems to have changed escape sequences for italics: [https://github.com/ThomasAd...](https://github.com/ThomasAdam/tmux/blob/master/FAQ#L355-L384 "https://github.com/ThomasAdam/tmux/blob/master/FAQ#L355-L384")

I haven't had any luck getting that to work though.

**Comment by alexpearce** [comment]
_Comment № 27 originally by Alex Pearce at 2015-11-03 08:16:01 UTC, replying to [a comment by Kenny Kaye at 2015-11-02 18:00:01 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512993)_.

I have the same problem; I've tried a few things but can't get italics to work. I'll write a post if I can figure something out.

**Comment by alexpearce** [comment]
_Comment № 28 originally by Joe Choi at 2015-12-10 22:08:05 UTC, replying to [a comment by Alex Pearce at 2015-11-03 08:16:01 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513022)_.

I put up a post on my blog how to get italics to work in tmux 2.1. Hope it helps!

[http://joehanchoi.com/quick...](http://joehanchoi.com/quick-fixes-for-tmux-2-1-on-osx/ "http://joehanchoi.com/quick-fixes-for-tmux-2-1-on-osx/")

**Comment by alexpearce** [comment]
_Comment № 29 originally by Brice at 2015-12-14 11:25:09 UTC, replying to [a comment by Alex Pearce at 2015-09-27 17:40:05 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512906)_.

I saw this behavior, at that time I wondered if this was related to El Capitan changes.

**Comment by alexpearce** [comment]
_Comment № 30 originally by cwalkatron at 2016-01-11 18:49:18 UTC, replying to [a comment by Alex Pearce at 2015-01-27 07:37:28 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781512386)_.

You can also add 

TERM screen-256color-italic to your 

~/.dircolors file.

**Comment by alexpearce** [comment]
_Comment № 31 originally by Andrew Janke at 2016-01-30 20:41:55 UTC_.

Should this snippet:

$ echo $TERM  
xterm-256-color-italic

be this instead?

$ echo $TERM  
xterm-256color-italic

That single character difference is probably significant for identifying the terminal type.

**Comment by alexpearce** [comment]
_Comment № 32 originally by Alex Pearce at 2016-02-01 15:43:52 UTC, replying to [a comment by Andrew Janke at 2016-01-30 20:41:55 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513140)_.

You're absolutely right, I've updated the post.

Thanks for pointing it out Andrew!

**Comment by alexpearce** [comment]
_Comment № 33 originally by Rafael Rinaldi at 2016-02-02 17:49:15 UTC_.

I have no idea what I'm doing wrong but following these steps made my   
iTerm 2 go crazy. I can't even open a new window if I set   
`xterm-256color-italic` under "report terminal type".

Anyone else ran into this or have any idea what the heck I'm doing wrong?

**Comment by alexpearce** [comment]
_Comment № 34 originally by Rafael Rinaldi at 2016-02-02 18:40:32 UTC, replying to [a comment by Rafael Rinaldi at 2016-02-02 17:49:15 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513196)_.

I've managed to fix it (thanks to the Fish shell community help). To properly override the $TERM variable in Fish, you should do: `set -g TERM xterm-256color-italic`

Thanks for this blog post!

**Comment by alexpearce** [comment]
_Comment № 35 originally by Alex Pearce at 2016-02-02 19:55:48 UTC, replying to [a comment by Rafael Rinaldi at 2016-02-02 18:40:32 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513227)_.

Good to hear, go Fish!

**Comment by alexpearce** [comment]
_Comment № 36 originally by Thomas Achtemichuk at 2016-02-11 15:51:10 UTC_.

Having an unrecognized $TERM has lead to a bunch of problems. I've found that installing a per-user override of xterm-256color to be much easier:

  
$ { infocmp -1 xterm-256color ; echo "\tsitm=\\E[3m,\n\tritm=\\E[23m,"; } > xterm-256color.terminfo  
$ tic xterm-256color.terminfo  
Now you get italics without all the workarounds for ssh or even changing your iTerm2 config.

**Comment by alexpearce** [comment]
_Comment № 37 originally by Jordan Running at 2016-04-24 21:55:35 UTC, replying to a since-deleted comment_.

Solved it for me! TL;DR: When tmux 2.1+ sees "screen" it disables italics. Name your terminfo "tmux-256color" instead of "screen-256color-italic."

**Comment by alexpearce** [comment]
_Comment № 38 originally by Alex Pearce at 2016-05-03 06:46:37 UTC, replying to a since-deleted comment_.

It was [base16-ocean](https://github.com/chriskempson/base16 "https://github.com/chriskempson/base16").

**Comment by alexpearce** [comment]
_Comment № 39 originally by Akash Shinde at 2016-07-20 08:42:02 UTC_.

nice post, thanks

**Comment by alexpearce** [comment]
_Comment № 40 originally by prashcr at 2016-08-14 03:07:53 UTC_.

I'm trying to enable italics in tmux and I get "tic: Can't open -" when I try to run the command above.

**Comment by alexpearce** [comment]
_Comment № 41 originally by Alex Pearce at 2016-08-15 08:11:31 UTC, replying to [a comment by prashcr at 2016-08-14 03:07:53 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513390)_.

Which command, exactly? There are a few tic commands in the article.

**Comment by alexpearce** [comment]
_Comment № 42 originally by CS Merritt at 2016-08-26 15:51:28 UTC, replying to [a comment by Thomas Achtemichuk at 2016-02-11 15:51:10 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513275)_.

echo -e   
The -e makes this work like a charm.  
Thanks for it.

**Comment by alexpearce** [comment]
_Comment № 43 originally by firedev at 2016-08-29 06:50:17 UTC, replying to [a comment by Alex Pearce at 2016-08-15 08:11:31 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513422)_.

```  
$ cat <<eof|tic -x="" -=""> tmux|tmux terminal multiplexer,  
> ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,  
> use=xterm+tmux, use=screen,  
>  
> tmux-256color|tmux with 256 colors,  
> use=xterm+256setaf, use=tmux,  
> EOF  
tic: Can't open -  
```

**Comment by alexpearce** [comment]
_Comment № 44 originally by Alex Pearce at 2016-08-30 07:07:50 UTC, replying to [a comment by firedev at 2016-08-29 06:50:17 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513477)_.

The either the formatting of the command has been messed up in the comment, or you're using a different command to what's in the post 😕

Either way, you should be able to save the contents of the terminfo (everything after the line with cat on and before the last line with EOF on) to some file, say tmux.terminfo, and then have tic load from that file.

$ tic -x tmux.terminfo

**Comment by alexpearce** [comment]
_Comment № 45 originally by Bennett at 2016-08-30 19:25:10 UTC, replying to [a comment by Thomas Achtemichuk at 2016-02-11 15:51:10 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513275)_.

Yes, thank you for this. $TERM errors when SSHing to servers that don't have my custom terminfo installed was becoming a big pain. Adding these steps to my .bashrc (using `echo -e` as CS Merritt mentions) saves the day.

**Comment by alexpearce** [comment]
_Comment № 46 originally by luigipertoldi at 2016-09-06 20:38:19 UTC_.

when I try to execute "tic -x tmux.terminfo" I get seg fault from my shell, what could it be?

**Comment by alexpearce** [comment]
_Comment № 47 originally by Mark Wilkinson at 2016-11-01 11:53:16 UTC, replying to [a comment by luigipertoldi at 2016-09-06 20:38:19 UTC](https://github.com/alexpearce/alexpearce.github.com/issues/23#issuecomment-781513564)_.

This worked for me: [http://apple.stackexchange....](http://apple.stackexchange.com/a/249385 "http://apple.stackexchange.com/a/249385")

Basically, replace "use=xterm+tmux" with "use=xterm" and "use=xterm+256setaf" with "xterm-256color".

**Comment by alexpearce** [comment]
_Comment № 48 originally by Zac at 2017-02-17 19:12:57 UTC_.

Very helpful stuff, thanks Alex.

I have been migrating my Vim configs to Neovim and found that 

highlight Comment cterm=italic didn't work. This is because my Neovim config uses 

settermguicolors (I believe nvim's default config comes with this setting).

Instead I used 

highlight Comment gui=italic and it worked right away (works for me inside tmux as well!)

**Comment by alexpearce** [comment]
_Comment № 49 originally by arcana of the succubus at 2017-06-22 17:19:48 UTC_.

I'm on tmux 2.5 and the 2.1+ fix works for me, but messes up some keys. For example I can't use the arrow keys in ctrlp in vim without it inserting into the buffer. For some reason vim depends on screen.

**Comment by alexpearce** [comment]
_Comment № 50 originally by Victor Kristof at 2017-07-14 19:18:24 UTC, replying to a since-deleted comment_.

This helped me on macOS Sierra: [https://apple.stackexchange...](https://apple.stackexchange.com/questions/249307/tic-doesnt-read-from-stdin-and-segfaults-when-adding-terminfo-to-support-italic/249385 "https://apple.stackexchange.com/questions/249307/tic-doesnt-read-from-stdin-and-segfaults-when-adding-terminfo-to-support-italic/249385")

**Comment by alexpearce** [comment]
_Comment № 51 originally by brankitodemunze at 2017-09-29 18:44:18 UTC_.

Thanks!

**Comment by cjsg** [comment]
Thanks for this awesome post. 

Just a short note for those using **tmux integration in iterm2**: I also had to disable the iterm2 option "Convert italics to reverse video in tmux integration?", under Preferences > Advanced (see Terminal section there).

**Comment by changtimwu** [comment]
It's been 7 years since the article published?  Just tried it on my NVIDIA Jetson and I'd like to say "every step works like a charm".

**Comment by JosephPall** [comment]
Thanks for this awesome post. i really appreciate your work on <a href="[https://](https://fontbots.com/cute-font-generator/) https://fontbots.com/italic-text-generator/  " >italic</a> font.It's a small but important detail that can make a big difference in the clarity and tone of your message
